name: LoveLovePlus
version: '${project.version}'
main: com.strangeone101.loveloveplus.Loveloveplus
api-version: 1.16
depend: [ ProjectKorra ]
authors: [ StrangeOne101 ]
softdepend: [LibsDisguises]
description: Adds the Love element!
